version: '3.8'

services:
  hello-world-app:
    image: hello-world-app
    ports:
      - "8000:8000"
    networks:
      - hello-world-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - hello-world-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3100:3000" # Map host port 3100 to container port 3000
    networks:
      - hello-world-network

networks:
  hello-world-network:
    driver: bridge
